package:
    name: mountainsort
    version: 4.3.0
build:
    number: 0
requirements:
    run:
        - mountainlab=0.15.2
        - mountainlab_pytools=0.7.5
        - ml_ms4alg=0.2.3
        - ml_ephys=0.2.14
        - ml_ms3=0.2.0

# extra:
#     copy_test_source_files: true
#     final: true
