package:
    name: mountainsort
    version: 4.1.0
build:
    number: 0
requirements:
    run:
        - ml_ephys=0.2.0
        - ml_ms3=0.0.1
        - ml_ms4alg=0.1.2
        - mountainlab=0.10.5
        - mountainlab_pytools=0.2.7
# extra:
#     copy_test_source_files: true
#     final: true
