{% set name = "ephys-viz" %}
{% set repo_owner = "flatironinstitute" %}
{% set version = "0.6.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ repo_owner }}/{{ name }}/archive/v{{ version }}.tar.gz

build:
  number: 2
  script:
    - test -n "$BUILT_FROM_TOPDIR" # error if not built from mountainlab-conda directory
    - tgzfile=$(npm pack)
    - npm install -g $tgzfile
    - python -m pip install vdom jp_proxy_widget
    - python -m pip install --no-deps --ignore-installed jp_ephys_viz

requirements:
  build:
    - python
    - pip
    - nodejs
  run:
    - python
    - nodejs
    - ipython
    - ipywidgets

test:
  commands:
    - npm list -g ephys-viz
    - which ev-timeseries
  requires:
    - nodejs

about:
  home: https://github.com/flatironinstitute/mountainlab-js
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

