{% set name = "isosplit5" %}
{% set version = "0.1.3" %}
{% set file_ext = "tar.gz" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}

build:
  number: 4
  script:
    - test -n "$BUILT_FROM_TOPDIR" # error if not built from mountainlab-conda directory
    - python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - pybind11 >=2.2
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - isosplit5

about:
  home: https://github.com/magland/isosplit5_python
  license: Apache 2
  license_family: APACHE
  license_file: ''
  summary: Efficient clustering algorithm for unknown number of unimodal clusters
  description: ''
  doc_url: ''
  dev_url: ''
