{% set name = "mountainlab_pytools" %}
{% set version = "0.2.6" %}
{% set file_ext = "tar.gz" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}

build:
  number: 2
  script:
    - test -n "$BUILT_FROM_TOPDIR" # error if not built from mountainlab-conda directory
    - python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - mountainlab
    - python
    - pip
    - requests
    - numpy
    - numpydoc
  run:
    - mountainlab
    - python
    - requests
    - numpy
    - numpydoc

test:
  imports:
    - mountainlab_pytools
    - mountainlab_pytools.mdaio
    - mountainlab_pytools.mlproc
    - mountainlab_pytools.processormanager

about:
  home: https://github.com/magland/mountainlab_pytools
  license: Apache Software
  license_family: APACHE
  license_file: ''
  summary: Tools for using MountainLab with python
  description: ''
  doc_url: ''
  dev_url: ''
