{% set repo_owner = "magland" %}
{% set name = "mountainlab_pytools" %}
{% set version = "0.7.5" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://github.com/{{ repo_owner }}/{{ name }}/archive/{{ version }}.tar.gz

build:
  number: 0
  script:
    - test -n "$BUILT_FROM_TOPDIR" # error if not built from mountainlab-conda directory
    # vdom + jp_proxy_widget are not available as conda packages, so we install pinned
    # versions with pip, then manually add the requirements (as conda packages) below.
    # conda-build > 3.17 sets PIP_NO_INDEX=True, but we actually want to go download
    # these packages in this case. (Hacky--should conda-ize them.)
    - PIP_NO_INDEX=False python -m pip install --no-deps --ignore-installed vdom==0.6 jp_proxy_widget==1.0.0
    - python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - mountainlab
    - python
    - pip
  run:
    - mountainlab
    - python
    - requests
    - numpy
    - numpydoc
    - requests # req'd by jp_proxy_widget
    - ipywidgets>=7.0.0 # req'd by jp_proxy_widget
    - ipython # req'd by vdom
    - jsonschema # req'd by vdom

test:
  imports:
    - mountainlab_pytools
    - mountainlab_pytools.mdaio
    - mountainlab_pytools.mlproc
    - mountainlab_pytools.processormanager
    - vdom
    - jp_proxy_widget

about:
  home: https://github.com/magland/mountainlab_pytools
  license: Apache Software
  license_family: APACHE
  license_file: ''
  summary: Tools for using MountainLab with python
  description: ''
  doc_url: ''
  dev_url: ''
