# NOTE PACKAGE NAME (mountainlab) DOES NOT MATCH REPO NAME (mountainlab-js)
{% set pkg_name = "mountainlab" %}
{% set repo_name = "mountainlab-js" %}
{% set repo_owner = "flatironinstitute" %}
{% set version = "0.15.1" %}

package:
  name: {{ pkg_name|lower }}
  version: {{ version }}

source:
   url: https://github.com/{{ repo_owner }}/{{ repo_name }}/archive/v{{ version }}.tar.gz

build:
  number: 1
  script:
    - test -n "$BUILT_FROM_TOPDIR" # error if not built from mountainlab-conda directory
    - tgzfile=$(npm pack)
    - npm install -g $tgzfile
    
    # set up mountainlab directories
    - mkdir -p "$PREFIX"/etc/mountainlab/{packages,database}
    - touch "$PREFIX"/etc/mountainlab/{packages,database}/.conda_keep # conda ignores empty directories

requirements:
  host:
    - nodejs
  run:
    - nodejs
    - coreutils [ osx ]

test:
  commands:
    - npm list -g mountainlab
    - ml-config
    - ml-list-processors
    - ml-spec hello.world
    - ml-spec hello.world -p
    - ml-run-process --help
    - ml-prv-locate --help
  requires:
    - nodejs

about:
  home: https://github.com/flatironinstitute/mountainlab
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

