# NOTE PACKAGE NAME (mountainlab) DOES NOT MATCH REPO NAME (mountainlab-js)
{% set pkg_name = "mountainlab" %}
{% set repo_name = "mountainlab-js" %}
{% set repo_owner = "flatironinstitute" %}
{% set version = "0.13.0" %}

package:
  name: {{ pkg_name|lower }}
  version: {{ version }}

source:
   url: https://github.com/{{ repo_owner }}/{{ repo_name }}/archive/v{{ version }}.tar.gz

build:
  number: 0
  script:
    - test -n "$BUILT_FROM_TOPDIR" # error if not built from mountainlab-conda directory
    - tgzfile=$(npm pack)
    - npm install -g $tgzfile

    # install activate scripts
    - mkdir -p "$PREFIX"/etc/conda/{de,}activate.d/
    - cp "${RECIPE_DIR}"/mountainlab_activate.sh "$PREFIX"/etc/conda/activate.d/
    - cp "${RECIPE_DIR}"/mountainlab_deactivate.sh "$PREFIX"/etc/conda/deactivate.d/

    # set up mountainlab directories
    - mkdir -p "$PREFIX"/etc/mountainlab/{packages,database}
    - touch "$PREFIX"/etc/mountainlab/{packages,database}/.conda_keep # conda ignores empty directories

requirements:
  host:
    - nodejs
  run:
    - nodejs
    - coreutils [ osx ]

test:
  commands:
    - npm list -g mountainlab
    - ml-config
    - ml-list-processors
  requires:
    - nodejs

about:
  home: https://github.com/flatironinstitute/mountainlab
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

