{% set name = "ml_pyms" %}
{% set repo_name = "mountainsort" %}
{% set repo_owner = "tjd2002" %}

# TODO:
# -rename source dir from pyms to ml_pyms? Currently a little hacky

package:
  name: {{ name }}
  version: "0.0.2"

source:
  git_url: https://github.com/{{ repo_owner }}/{{ repo_name}}
  git_rev: conda-build

requirements:
  build:
    - {{ compiler('cxx') }}
    - intel-openmp    # [linux]
    - llvm-openmp     # [osx]
  host:
    - python
    - pip
    - pybind11 >=2.2
    - fftw
    - mountainlab     # provides install locations, must be in host
  run:
    - python
    - intel-openmp    # [linux]
    - llvm-openmp     # [osx]
    - fftw
    - mountainlab
    - numpy
    - numpydoc
    - scipy
    - matplotlib
    - scikit-learn

build:
  number: 0
  script:
    - set -e -u - x -o pipefail
    - test -n "$BUILT_FROM_TOPDIR" # error if not built from mountainlab-conda directory

    - cd packages
    - python -m pip install --no-deps --ignore-installed .
    # link python package to mountainlab packages dir so processors will be discovered
    # Note: need to give ml-config the right CONDA_PREFIX value
    - echo ln -sf $SP_DIR/pyms `CONDA_PREFIX=$PREFIX ml-config package_directory`/{{ name }}
    - ln -sf $SP_DIR/pyms `CONDA_PREFIX=$PREFIX ml-config package_directory`/{{ name }}

test:
  commands:
    - ml-list-processors
    - ml-spec pyms.extract_clips
    - python -c "from  pyms.basic.p_compute_templates import compute_templates_helper"
    
about:
  home: https://github.com/flatironinstitute/mountainsort
  license: Apache 2.0
  summary: Legacy (v3) mountainsort processor for mountainlab
