{% set name = "ml_pyms" %}
{% set repo_name = "mountainsort" %}
{% set repo_owner = "flatironinstitute" %}
{% set version = "0.2.1" %}

# TODO:
# -rename source dir from pyms to ml_pyms? Currently a little hacky

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ repo_owner }}/{{ repo_name }}/archive/v{{ version }}.tar.gz


requirements:
  build:
    - {{ compiler('cxx') }}
    - intel-openmp    # [linux]
    - llvm-openmp     # [osx]
  host:
    - python
    - pip
    - pybind11 >=2.2
    - fftw
    - intel-openmp    # [linux]
    - llvm-openmp     # [osx]
    - mountainlab>=0.15     # provides install locations, must be in host
  run:
    - python
    - intel-openmp    # [linux]
    - llvm-openmp     # [osx]
    - fftw
    - mountainlab>=0.15
    - numpy
    - numpydoc
    - scipy
    - matplotlib
    - scikit-learn

build:
  number: 3
  script:
    - set -e -u - x -o pipefail
    - test -n "$BUILT_FROM_TOPDIR" # error if not built from mountainlab-conda directory
    - ML_PACKAGE_DIR=`CONDA_PREFIX=$PREFIX ml-config package_directory`
    - test -n "$ML_PACKAGE_DIR" # error if we can't find package directory

    - cd packages
    - python -m pip install --no-deps --ignore-installed .
    # link python package to mountainlab packages dir so processors will be discovered
    - ln -sf $SP_DIR/pyms $ML_PACKAGE_DIR/ml_pyms

test:
  imports:
    - pyms.basic.p_compute_templates
  commands:
    - ml-list-processors
    - ml-spec pyms.extract_clips
    
about:
  home: https://github.com/flatironinstitute/mountainsort
  license: Apache 2.0
  summary: Legacy (v3) mountainsort processor for mountainlab
