{% set name = "ml_ephys" %}
{% set version = "0.2.1" %}
{% set repo_owner = "magland" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://github.com/{{ repo_owner }}/{{ name }}/archive/{{ version }}.tar.gz

build:
  number: 0
  script:
    - test -n "$BUILT_FROM_TOPDIR" # error if not built from mountainlab-conda directory
    - python -m pip install --no-deps --ignore-installed .
    # link python package to mountainlab packages dir so processors will be discovered
    - ln -sf $SP_DIR/{{ name }} $ML_CONDA_PACKAGES_DIR
    
requirements:
  host:
    - python
    - pip
    - mountainlab_pytools
    - mountainlab
    - deepdish
    - scipy
    - numpy
    - numpydoc
    - h5py
  run:
    - mountainlab
    - python
    - mountainlab_pytools
    - deepdish
    - scipy
    - numpy
    - numpydoc
    - h5py

test:
  imports:
    - ml_ephys
    - ml_ephys.basic
    - ml_ephys.preprocessing
    - ml_ephys.synthesis
    - ml_ephys.validation

about:
  home: https://github.com/magland/ml_ephys
  license: Apache Software
  license_family: APACHE
  license_file: ''
  summary: ephys tools for MountainLab
  description: "ml_ephys\n\nElectrophysiology tools\nMountainLab processor library"
  doc_url: ''
  dev_url: ''
