{% set name = "ml_ms4alg" %}
{% set repo_owner = "magland" %}
{% set version = "0.1.2" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://github.com/{{ repo_owner }}/{{ name }}/archive/{{ version }}.tar.gz

build:
  number: 6 
  script:
    - test -n "$BUILT_FROM_TOPDIR" # error if not built from mountainlab-conda directory
    - python -m pip install --no-deps --ignore-installed .
    # link python package to mountainlab packages dir so processors will be discovered
    - ln -sf $SP_DIR/{{ name }} $ML_CONDA_PACKAGES_DIR

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - pybind11
    - isosplit5
    - numpy
    - mountainlab
    - mountainlab_pytools
    - h5py

  run:
    - python
    - numpy
    - h5py
    - mountainlab
    - mountainlab_pytools
    - isosplit5
    
test:
  imports:
    - ml_ms4alg
  commands:
    - ml-list-processors
    - ml-spec ms4alg.sort

about:
  home: https://github.com/magland/ml_ms4alg
  license: Apache Software
  license_family: APACHE
  license_file: ''
  summary: Mountainsort v4 processor plugin for MountainLab
  description: "ml_ms4alg\n\nMountainSort v4\nMountainLab processor library"
  doc_url: ''
  dev_url: ''
