# TODO:
# -pin openmp build/run?

package:
  name: ml_ms3
  version: "0.0.2"

source:
  git_url: https://github.com/flatironinstitute/mountainsort
  git_rev: master

requirements:
  build:
    - {{ compiler('cxx') }}
    - intel-openmp    # [linux]
    - llvm-openmp     # [osx]
  host:
    - qt {{ qt }}     # see ./conda_build_config.yaml for Qt variants specification
    - fftw            # libraries to be linked, must be in host and run?
    - mountainlab     # provides install locations, must be in host
  run:
    - intel-openmp    # [linux]
    - llvm-openmp     # [osx]
    - fftw
    - mountainlab
    - qt

build:
  number: 0
  script:
    - set -e -u - x -o pipefail
    - test -n "$BUILT_FROM_TOPDIR" # error if not built from mountainlab-conda directory

    # These should both be set in mountainlab-conda/conda_build_config.yaml
    - test -d "${CONDA_BUILD_SYSROOT}" # [osx]
    - test -d "${XC_AVOIDANCE_PATH_QT}" # [osx]
    - export PATH=$XC_AVOIDANCE_PATH_QT:$PATH # [osx]
    
    # Include host env's /include to pick up fftw.
    # CONFIG-=App_bundle should go in ms3.pro instead
    - qmake INCLUDEPATH+=$PREFIX/include CONFIG-=app_bundle # [osx]
    - qmake INCLUDEPATH+=$PREFIX/include # [not osx]
    - make -j${CPU_COUNT} sub-packages-ms3-ms3-pro 
    # Note: need to give ml-config the right CONDA_PREFIX value
    - cp packages/ms3/bin/ms3.mp `CONDA_PREFIX=$PREFIX ml-config package_directory`/

test:
  commands:
    - ml-list-processors
    - ml-spec ms3.isolation_metrics
    
about:
  home: https://github.com/flatironinstitute/mountainsort
  license: Apache 2.0
  summary: Legacy (v3) mountainsort processor for mountainlab
