{% set name = "ml_ms3" %}
{% set repo_name = "mountainsort" %}
{% set repo_owner = "flatironinstitute" %}
{% set version = "0.2.4" %}

# TODO:
# -pin openmp build/run?

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ repo_owner }}/{{ repo_name }}/archive/v{{ version }}.tar.gz

requirements:
  build:
    - {{ compiler('cxx') }}
    - openmp
  host:
    - qt {{ qt }}     # see ./conda_build_config.yaml for Qt variants specification
    - fftw            # libraries to be linked, must be in host and run?
    - openmp
    - mountainlab>=0.15 # provides install locations, must be in host
  run:
    - openmp
    - fftw
    - mountainlab>=0.15
    - qt

build:
  number: 1
  script:
    - set -e -u - x -o pipefail
    - test -n "$BUILT_FROM_TOPDIR" # error if not built from mountainlab-conda directory
    - ML_PACKAGE_DIR=`CONDA_PREFIX=$PREFIX ml-config package_directory`
    - test -n "$ML_PACKAGE_DIR" # error if we can't find package directory

    # These should both be set in mountainlab-conda/conda_build_config.yaml
    - test -d "${CONDA_BUILD_SYSROOT}" # [osx]
    - test -d "${XC_AVOIDANCE_PATH_QT}" # [osx]
    - export PATH=$XC_AVOIDANCE_PATH_QT:$PATH # [osx]
    
    # Include host env's /include to pick up fftw.
    - qmake INCLUDEPATH+=$PREFIX/include
    - make -j${CPU_COUNT}

    # Install in mountainlab packages directory
    - cp packages/ms3/bin/ms3.mp "$ML_PACKAGE_DIR"
    - cp packages/mountainsortalg/bin/mountainsortalg.mp "$ML_PACKAGE_DIR"/ms3alg.mp

test:
  commands:
    - ml-list-processors
    - ml-spec ms3.isolation_metrics
    - ml-spec mountainsortalg.ms3alg
    
about:
  home: https://github.com/flatironinstitute/mountainsort
  license: Apache 2.0
  summary: Legacy (v3) mountainsort processor for mountainlab
