# conda-build packaging config for qt-mountainview
{% set name = "qt-mountainview" %}
{% set repo_owner = "flatironinstitute" %}
{% set version = "0.1.3" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://github.com/{{ repo_owner }}/{{ name }}/archive/v{{ version }}.tar.gz

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - qt {{ qt }}     # see ../conda_build_config.yaml for variants specification
    - mountainlab  # provides install locations
  run:
    - qt              # ../conda_build_config.yaml pins run & build Qt versions
    - mountainlab>=0.15

build:
  number: 6
  script:
    - set -e -u - x -o pipefail
    - test -n "$BUILT_FROM_TOPDIR" # error if not built from mountainlab-conda directory
    - ML_PACKAGE_DIR=`CONDA_PREFIX=$PREFIX ml-config package_directory`
    - test -n "$ML_PACKAGE_DIR" # error if empty string
    - test -d "$ML_PACKAGE_DIR" # error if not a directory
    
    # These should both be set in mountainlab-conda/conda_build_config.yaml
    - test -d "${CONDA_BUILD_SYSROOT}" # [osx]
    - test -d "${XC_AVOIDANCE_PATH_QT}" # [osx]
    - export PATH=$XC_AVOIDANCE_PATH_QT:$PATH # [osx]

    - qmake -r  # don't need CONFIG+=standalone, conda handles binary relocation! (linux + mac)
    - make -j${CPU_COUNT}
    - make install
    - cp packages/mv/bin/mv.mp "$ML_PACKAGE_DIR"
    - cp bin/qt-mountainview "${PREFIX}"/bin

test:
  commands:
    - which qt-mountainview
    - ml-list-processors
    - ml-spec mv.create_multiscale_timeseries

about:
  home: https://github.com/flatironinstitute/qt-mountainview
  license: Apache 2.0
  summary: Visualization of spike sorting experiments to be used as a plugin package to mountainlab
